language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
 - docker-compose run -u root app sh -c "python manage.py wait_for_db && coverage run --source=. manage.py test && flake8 && coverage report -m"
#after_success:
# - docker-compose run -u root app sh -c "coveralls"
