# Generated by Django 3.2.5 on 2021-08-05 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210802_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField()),
                ('exit_datetime', models.DateTimeField()),
                ('attendee_email', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.building')),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['attendee_email'], name='attendee_email_index'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['entry_datetime', 'exit_datetime'], name='entry_and_exit_attendee_index'),
        ),
    ]
