# Generated by Django 3.2.5 on 2021-08-05 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210804_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
    ]
